workspace:
  base: /drone
  path: src/github.com/qnib/qframe-handler-elasticsearch

pipeline:
  clone:
    image: plugins/git
    tags: true
  test:
    image: qnib/uplain-golang
    pull: true
    commands:
     - govendor fetch +e
     - govendor update +l
     - go build -ldflags "-pluginpath=qframe-handler-elasticsearch" -buildmode=plugin -o elasticsearch.so main.go
    environment:
     - GOPATH=/drone/
